name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  IMAGE_NAME: particula-mqtt-broker
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: "${{ github.actor }}"
        password: "${{ secrets.GITHUB_TOKEN }}"
        image_name: vives-projectwerk-2-2020/mqtt-broker/particula-mqtt-broker
        image_tag: master
        registry: docker.pkg.github.com
        
  deploy:
    name: deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOYMENT_SERVER_HOST }}
        username: ${{ secrets.DEPLOYMENT_SERVER_USERNAME }}
        key: ${{ secrets.DEPLOYMENT_SERVER_KEY }}
        port: ${{ secrets.DEPLOYMENT_SERVER_PORT }}
        script: |
          cd ${{ secrets.DEPLOYMENT_SERVER_PATH }}
          docker-compose pull mqtt
          docker-compose up -d mqtt
